[build]
  command = "npm run build"
  publish = "build"

[functions]
  directory = "netlify/functions"
  external_node_modules = ["undici"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
